#配置内嵌的tomcat端口
server:
  port: 8080

##配置数据库连接信息
#spring:
#  datasource:
#    url: jdbc:mysql://59.110.115.75:3306/intelligent_education_db?useUnicode=true&characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: wqh
#    password: Wqh171717

#配置数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiangyun?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wqh594188

  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com

    
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: linyao_186@163.com
    #授权码
    password: IHTMDCPECTJKOYJJ
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          # 指定端口为465
          port: 465
          # 指定socketFactory端口为465
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

  #配置redis连接信息
  data:
    redis:
      host: 59.110.115.75
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 8        # 连接池最大连接数(使用负值表示没有限制） 默认8
          max-wait: -1         #连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-idle: 8          #连接池最大空闲连接 默认8
          min-idle: 0          #连接池最小空闲连接 默认 0
      connect-timeout: 5000
      password: 123456
#指定Mapper.xml文件的位置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #在控制台打印出sql语句的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自定义配置
rebox:
  jwt:
    secret: Q9ejs^eP0uIwe(53E21pYT

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.rebox.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn